-- MySQL Script generated by MySQL Workbench
-- Wed Mar 25 16:39:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Team10
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Team10
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Team10` DEFAULT CHARACTER SET utf8 ;
USE `Team10` ;

-- -----------------------------------------------------
-- Table `Team10`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team10`.`Department` (
  `Department_ID` INT NOT NULL AUTO_INCREMENT,
  `Department_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Department_ID`),
  UNIQUE INDEX `Department_ID_UNIQUE` (`Department_ID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team10`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team10`.`Staff` (
  `Staff_ID` INT NOT NULL AUTO_INCREMENT,
  `Department_ID` INT NOT NULL,
  `First_Name` VARCHAR(32) NOT NULL,
  `Last_Name` VARCHAR(32) NOT NULL,
  `Job_Title` VARCHAR(32) NOT NULL,
  `Email_Address` VARCHAR(128) NOT NULL,
  `Home_Address` VARCHAR(256) NOT NULL,
  `Salary` FLOAT NOT NULL,
  `Start_Date` DATE NOT NULL,
  PRIMARY KEY (`Staff_ID`),
  INDEX `fk_STAFF_Department1_idx` (`Department_ID` ASC) ,
  UNIQUE INDEX `Staff_ID_UNIQUE` (`Staff_ID` ASC) ,
  CONSTRAINT `Department_ID`
    FOREIGN KEY (`Department_ID`)
    REFERENCES `Team10`.`Department` (`Department_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 4;


-- -----------------------------------------------------
-- Table `Team10`.`Exhibit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team10`.`Exhibit` (
  `Exhibit_ID` INT NOT NULL,
  `Department_ID` INT NOT NULL,
  `Animal_ID` INT NOT NULL,
  `Name` VARCHAR(32) NOT NULL,
  `Exhibit_Habitat` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Image_URL` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Exhibit_ID`),
  INDEX `fk_EXHIBIT_Department1_idx` (`Department_ID` ASC) ,
  CONSTRAINT `fk_EXHIBIT_Department1`
    FOREIGN KEY (`Department_ID`)
    REFERENCES `Team10`.`Department` (`Department_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team10`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team10`.`Animal` (
  `Animal_ID` INT NOT NULL,
  `Exhibit_ID` INT NOT NULL,
  `Name` VARCHAR(32) NOT NULL,
  `Class` VARCHAR(32) NOT NULL,
  `Birthdate` DATETIME NOT NULL,
  `Last_Checkup` DATETIME NOT NULL,
  `Weight` DECIMAL NOT NULL,
  `Gender` TINYINT NOT NULL,
  `Short_Description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Animal_ID`),
  INDEX `fk_Animal_Exhibit1_idx` (`Exhibit_ID` ASC) ,
  CONSTRAINT `fk_Animal_Exhibit1`
    FOREIGN KEY (`Exhibit_ID`)
    REFERENCES `Team10`.`Exhibit` (`Exhibit_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team10`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team10`.`Customer` (
  `Customer_ID` INT NOT NULL,
  `First_Name` VARCHAR(32) NOT NULL,
  `Last_Name` VARCHAR(32) NOT NULL,
  `Phone_Number` VARCHAR(32) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Street_Name` VARCHAR(255) NOT NULL,
  `Zip_Code` INT NOT NULL,
  `City` VARCHAR(50) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team10`.`Gift_Shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team10`.`Gift_Shop` (
  `Shop_ID` INT NOT NULL,
  `Department_ID` INT NOT NULL,
  `Shop_Name` VARCHAR(32) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Image_URL` VARCHAR(255) NOT NULL,
  `Location` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Shop_ID`),
  INDEX `fk_Shop_Department1_idx` (`Department_ID` ASC) ,
  CONSTRAINT `fk_Shop_Department1`
    FOREIGN KEY (`Department_ID`)
    REFERENCES `Team10`.`Department` (`Department_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team10`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team10`.`Event` (
  `Event_ID` INT NOT NULL,
  `Department_ID` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Location` VARCHAR(255) NOT NULL,
  `Image_URL` VARCHAR(255) NOT NULL,
  `Description` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`Event_ID`),
  INDEX `fk_Public Events_Department1_idx` (`Department_ID` ASC) ,
  CONSTRAINT `fk_Public Events_Department1`
    FOREIGN KEY (`Department_ID`)
    REFERENCES `Team10`.`Department` (`Department_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team10`.`Private_Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team10`.`Private_Event` (
  `Event_ID` INT NOT NULL AUTO_INCREMENT,
  `Department_ID` INT NOT NULL,
  `Event_Date` DATETIME NOT NULL,
  `Price` FLOAT NOT NULL,
  `Guest_Capacity` INT NOT NULL,
  `Location` VARCHAR(255) NOT NULL,
  `Event_Type` VARCHAR(255) NOT NULL,
  `Image_URL` VARCHAR(255) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Is_Booked` TINYINT NOT NULL,
  PRIMARY KEY (`Event_ID`),
  UNIQUE INDEX `Event_ID_UNIQUE` (`Event_ID` ASC) ,
  INDEX `fk_Private Events_Department1_idx` (`Department_ID` ASC) ,
  CONSTRAINT `fk_Private_Event_Department1`
    FOREIGN KEY (`Department_ID`)
    REFERENCES `Team10`.`Department` (`Department_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team10`.`Ticket_Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team10`.`Ticket_Purchase` (
  `Transaction_ID` INT NOT NULL,
  `Customer_ID` INT NOT NULL,
  `Ticket_ID` INT NOT NULL AUTO_INCREMENT,
  `Price` FLOAT NOT NULL,
  `Expiration_Date` DATETIME NOT NULL,
  `Purchase_Date` DATETIME NOT NULL,
  `Is_Valid` TINYINT NOT NULL,
  INDEX `Customer_ID_idx` (`Customer_ID` ASC) ,
  PRIMARY KEY (`Ticket_ID`),
  CONSTRAINT `Customer_ID`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `Team10`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team10`.`Private_Event_Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team10`.`Private_Event_Purchase` (
  `Transaction_ID` INT NOT NULL,
  `Event_ID` INT NOT NULL,
  `Customer_ID` INT NOT NULL,
  `Pass_ID` INT NOT NULL,
  `Total_Cost` INT NOT NULL,
  `Purchase_Date` DATETIME NOT NULL,
  `Is_Valid` TINYINT NOT NULL,
  PRIMARY KEY (`Transaction_ID`),
  INDEX `Event_ID_idx` (`Event_ID` ASC) ,
  INDEX `Customer_ID_idx` (`Customer_ID` ASC) ,
  CONSTRAINT `fk_Private_Event_Purchase_Event1`
    FOREIGN KEY (`Event_ID`)
    REFERENCES `Team10`.`Private_Event` (`Event_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Private_Event_Purchase_Customer1`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `Team10`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team10`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team10`.`Items` (
  `Item_ID` INT NOT NULL,
  `Shop_ID` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Image_URL` VARCHAR(45) NOT NULL,
  `Price` FLOAT NOT NULL,
  `Stock_Count` INT NOT NULL,
  PRIMARY KEY (`Item_ID`),
  INDEX `Shop_ID_idx` (`Shop_ID` ASC) ,
  CONSTRAINT `Shop_ID`
    FOREIGN KEY (`Shop_ID`)
    REFERENCES `Team10`.`Gift_Shop` (`Shop_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team10`.`Item_Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team10`.`Item_Purchase` (
  `Transaction_ID` INT NOT NULL AUTO_INCREMENT,
  `Item_ID` INT NOT NULL,
  `Customer_ID` INT NOT NULL,
  `Total_Cost` FLOAT NOT NULL,
  `Purchase_Date` DATETIME NOT NULL,
  `Quanitity` INT NOT NULL,
  PRIMARY KEY (`Transaction_ID`),
  INDEX `Item_ID_idx` (`Item_ID` ASC) ,
  INDEX `Customer_ID_idx` (`Customer_ID` ASC) ,
  CONSTRAINT `fk_Item_Purchase_item1`
    FOREIGN KEY (`Item_ID`)
    REFERENCES `Team10`.`Items` (`Item_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Purchase_customer1`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `Team10`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

#CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
